{% set name = "tifffile" %}
{% set version = "2025.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e437c16ab211be5bcdc79f71b4907359115f1f83b5d919e7c297c29725d3e38

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
  run_constrained:
    # 'codecs'
    - imagecodecs >=2024.12.30
    # 'zarr'
    - zarr >=3.1.3

# Skip due to AssertionsError - no presence of newline. This is a test issue.
# Also skip test_func_pformat_xml on Windows due to quote style mismatch.
{% set skipped_tests = [
    "test_class_omexml_modulo",
    "test_class_omexml_attributes", 
    "test_class_omexml_datasets",
    "test_class_omexml_multiimage"
] %}
{% set skipped_tests_win = ["test_class_omexml", "test_func_pformat_xml"] %}

test:
  source_files:
    - tests
  imports:
    - tifffile
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - tifffile --help
    - tiff2fsspec --help
    - pytest -v tests/ -k "not {{ ' and not '.join(skipped_tests) }}"  # [not win]
    - pytest -v tests/ -k "not {{ ' and not '.join(skipped_tests_win) }}"  # [win]

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Tifffile is a Python library to store NumPy arrays in TIFF (Tagged Image File Format) files, and read image and metadata from TIFF-like files used in bioimaging.
  summary: Read and write image data from and to TIFF files.
  doc_url: https://github.com/cgohlke/tifffile/blob/master/README.rst
  dev_url: https://github.com/cgohlke/tifffile

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
