{% set name = "tifffile" %}
{% set version = "2025.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c38e929bf74c04b6c8708d87f16b32c85c6d7c2514b99559ea3db8003ba4edda

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
  run_constrained:
    - matplotlib-base >=3.10
    # imagecodecs shouldn't be used in run as it will become a circular dependency
    - imagecodecs >=2023.8.12 # extra:codecs
    - zarr <3 # extra:zarr

test:
  imports:
    - tifffile
  requires:
    - pip
  commands:
    - pip check
    - tifffile --help
    - tiff2fsspec --help

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
      Tifffile is a Python library to store NumPy arrays in TIFF (Tagged Image File Format) files, and read image and metadata from TIFF-like files used in bioimaging.
  summary: Read and write image data from and to TIFF files.
  doc_url: https://github.com/cgohlke/tifffile/blob/master/README.rst
  dev_url: https://github.com/cgohlke/tifffile

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
