{% set version = "0.11.0" %}

package:
  name: tifffile
  version: {{ version }}

source:
  fn: tifffile-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: b3dc2eac0c18dc5d0693e5a8dd9e3ec61fe4710f78603a45787111f613b2cee9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - msinttypes  # [win and py<35]
  run:
    - python
    - numpy x.x

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read and write image data from and to TIFF files.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
    - stuarteberg
