{% set version = "2020.9.22" %}

package:
  name: tifffile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: 505a0ddf372697e8dacd3a8bc486f7143df44772b0fd72ca56486b6b46cbe494

build:
    number: 2
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools_scm
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - backports.lzma  # [py27]
    - futures  # [py27]
    - enum34  # [py27]
    - pathlib  # [py27]

test:
  imports:
    - tifffile
  commands:
    - conda inspect linkages -p $PREFIX tifffile  # [not win]
    - conda inspect objects -p $PREFIX tifffile  # [osx]

about:
  home: https://github.com/blink1073/tifffile
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Read and write image data from and to TIFF files.'

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
    - jakirkham
    - stuarteberg
