{% set name = "tifffile" %}
{% set version = "2021.11.2" %}
{% set sha256 = "153e31fa1d892f482fabb2ae9f2561fa429ee42d01a6f67e58cee13637d9285b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  # there is a missing dependency for s390x imagecodecs version >=2021.4.28 
  skip: True  # [py<37 or s390x]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - numpy >=1.15.1
    # Extras require:
    - imagecodecs >=2021.4.28

test:
  imports:
    - tifffile
  requires:
    - python <3.10
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.
  doc_url: https://github.com/cgohlke/tifffile/blob/master/README.rst
  dev_url: https://github.com/cgohlke/tifffile

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
