{% set name = "tifffile" %}
{% set version = "2026.6.1" %}
{% set skipped_tests = [
  "test_class_omexml_modulo",
  "test_class_omexml_attributes",
  "test_class_omexml_datasets",
  "test_class_omexml_multiimage"
] %}
{% set skipped_tests_win = [
  "test_class_omexml",
  "test_func_pformat_xml"
] %}

# Skip due to AssertionsError - no presence of newline. This is a test issue.
# Also skip test_func_pformat_xml on Windows due to quote style mismatch.
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 626c892c0e899d959b9438e7c0e1491dc154a7fead1f1f37a991724a50eceba9

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  entry_points:
    - tifffile = tifffile:main
    - tiffcomment = tifffile.tiffcomment:main
    - tiff2fsspec = tifffile.tiff2fsspec:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=2.1
  run_constrained:
    # 'codecs'
    - imagecodecs >=2026.5.10
    # 'zarr'
    - zarr >=3.2.0

test:
  source_files:
    - tests
  imports:
    - tifffile
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - tifffile --help
    - tiff2fsspec --help
    - pytest -v tests/ -k "not {{ ' and not '.join(skipped_tests) }}"  # [not win]
    - pytest -v tests/ -k "not {{ ' and not '.join(skipped_tests_win) }}"  # [win]

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    Tifffile is a Python library to store NumPy arrays in TIFF (Tagged Image File Format) files, and read image and metadata from TIFF-like files used in bioimaging.
  summary: Read and write image data from and to TIFF files.
  doc_url: https://github.com/cgohlke/tifffile/blob/master/README.rst
  dev_url: https://github.com/cgohlke/tifffile

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
