travis:
  secure:
    BINSTAR_TOKEN: YZm8IXgtRLdSAltpGOjlQrrFxqEZB/jD6GMdnpAqe4hI/7p+0JPCl8gfaWrnL6jI0SkN4K3j5lajPh5cIZLDFkWfjgpqDoSG9mbC9TV2/UwEwUabekG4qTDb2HyNCAd+Gok84R5gxFvFX7yEsYzOgSvZlD9DIH7gMW74yCnQDohfP5dgWFNYlxIns2jfz6vZv/CDEN4Ajuq44cjptPVkmRZBnt4NNDPdqi9fcNBmWwESpZxEgtlsIh0yUSlDK9wPBd7KxQ+4mmLrBQkcZVsJDRJTFNUmPdkIleY9JmjITu+1iC2/Du1ZE7DUtHFrKbBW8yQ+Ff6xg22hrZYv5UULWa+5GLdb/+OX7A6ZmJYolM755suTy5JF05B4+9KrcjyA9gTwNXHbTYIP/VF1fRgfMVJmJs0smQs4aKUo7OQWzfUxu251NMUkEwMhYuDNdBo2aZ5SolJgliCqCPy3I7cnZr2Fk1YPshG/VAcZt9SllVjufdWCQ6cU6sgrPEeDhXIDvNYfdx06fl+QaUnV8UVfL2RhbEi4bdlJazVSOKTkpauw+z35hRAdFxzaFg1xTT56s0/WIRMmAPZaxjLZk90JAHv2j7fZM62GcCBVekjP0bi7A8aW/JuPFF/FykawXx0ZcBXmsOlYRnYn0qSarYf5H8Rt+0RMwOppAxllywgGEM0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
